spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service
# this is what OrderService @Value("${products.base-url:...}") reads
products:
  base-url: http://localhost:8080

server:
  port: 8083


