spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: payment-service

server:
  port: 8084




