spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itemdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: item-service

server:
  port: 8082




